### ISSUE TITLE
Broken links in after actions menu

### ISSUE THREAD

**Issue by gbp** [mysociety/kimittud-theme#1]
Follow up ("Válasz az adatgazdának") and respond to request ("Válasz az adatigénylésre") links are broken.

They are using the request url title instead of ID.

For 0.44
This is broken: https://kimittud.hu/request/eltex_kft_hadhazi_hulladekfeldol_2/followups/new/35449
This works: https://kimittud.hu/request/24911/followups/new/35449

**Comment by gbp** [comment]
Need to reconcile theme with core. Could down to originally using the develop branch locally when I was working on this

**Comment by gbp** [comment]
This was fixed in 7c24e4620a41c4966873f5830821f8d16159a515

**Comment by pdng** [comment]
we tested, works, thank you
