### ISSUE TITLE
[ERROR] request#show (invalid byte sequence in UTF-8)

### ISSUE THREAD

**Issue by gbp** [mysociety/kimittud-theme#2]
```
An ActionView::Template::Error occurred in request#show:

  invalid byte sequence in UTF-8
  app/models/incoming_message.rb:374:in `gsub'


-------------------------------
Request:
-------------------------------

  * URL        : http://kimittud.hu/request/ketpoi_vonatbaleset_gysev?nocache=incoming-35432
  * HTTP Method: GET
  * Parameters : {"nocache"=>"incoming-35432", "controller"=>"request", "action"=>"show", "url_title"=>"ketpoi_vonatbaleset_gysev"}
  * Timestamp  : 2024-06-25 14:15:49 +0200
  * Server : [kimittud.hu](http://kimittud.hu/)
```

**Comment by pdng** [comment]
we have the same problem here

the requester cannot open the request, the attachment cannot be donwloaded from the admin

https://kimittud.hu/request/godi_ipari_innovacios_terulet_va#incoming-35464

**Comment by pdng** [comment]
this is a high priority problem, as we cannot check several FOI answers

**Comment by gbp** [comment]
Appears this is due to `elinks` convertsion of HTML into plain text. Adding a call to our existing `convert_string_to_utf8` helper method seems to fix this.

I will get this added via the theme.

```ruby
def convert_to_plain_text_with_elinks(body)
  # taken from https://github.com/mysociety/alaveteli/blob/0949ffe5b6b8a52e6a6ff2d27a3d0fa4940d6951/lib/mail_handler.rb#L74-L80
  tempfile = Tempfile.new('foiextract')
  tempfile.binmode; tempfile.print(body)
  tempfile.flush
  text = ""
  default_params = { append_to: text, binary_output: false, timeout: 1200 }

  # taken from https://github.com/mysociety/alaveteli/blob/0949ffe5b6b8a52e6a6ff2d27a3d0fa4940d6951/lib/mail_handler.rb#L98-L103
  AlaveteliExternalCommand.run(
    "elinks",
    "-eval", "set document.codepage.assume = \"utf-8\"",
    "-eval", "set document.codepage.force_assumed = 1",
    "-dump-charset", "utf-8",
    "-force-html", "-dump",
    tempfile.path,
    default_params.merge(env: { "LANG" => "C" })
  )
end

message = IncomingMessage.find(35432)
mail_part = message.get_main_body_text_part
html_body = mail_part.body_as_text.string
html_body.valid_encoding? # => true

text_body = convert_to_plain_text_with_elinks(html_body)
text_body.valid_encoding? # => false

convert_string_to_utf8(text_body, 'UTF-8').string.valid_encoding? # => true
```

**Comment by pdng** [comment]
Hi, we tested, and works fine, so the main error is handled, thank you - but still some coding problem, if you check the last message in this request https://kimittud.hu/request/ketpoi_vonatbaleset_gysev#incoming-35432 it is not correctly coded (though all the other messages are)

Could you please check this?

**Comment by gbp** [comment]
Ultimately the message received has been encoded incorrectly. Are attempt to work around the issue in 247d2fcb70614a4fd90f5bde007331fe2343c690 caused the further encoding issue.

The simplest solution would be to scrub the message of invalid bytes these will then appear as � but this is probably the better solution as it will mean more of the message is readable.

For the case above the invalid bytes seem to be in the quoted section of the message anyway.

**Comment by gbp** [comment]
FWIW Apple Mail silently drop the invalid characters in the message above.
